In [1]:
import numpy as np
import time

In [2]:
arr=np.array([1,2,3,4,5])
print(arr,type(arr),arr.shape)
arr2=np.array([1,2,3,4,"prime"])
print(arr2,type(arr2),arr2.shape)
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D,arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' 'prime'] <class 'numpy.ndarray'> (5,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [3]:
arr1=np.zeros((2,3),dtype="int64") #prefill
print(arr1,arr1.shape)
arr2=np.ones(5,) #prefill
print(arr2,arr2.shape)
arr3=np.full((3,4),100) #prefill with given val
print(arr3,arr3.shape)
arr4=np.eye(3) #identity matrix
print(arr4)
arr5=np.arange(0,11,2) #range
print(arr5,arr5.shape)
arr6=np.linspace(1,100,4) #evenly spaced arrays
print(arr6,arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 0  2  4  6  8 10] (6,)
[  1.  34.  67. 100.] (4,)


In [6]:
#array properties
arr=np.array([[1,2,3],[4,5,6],[7,8,9]]) 
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr=arr.astype(np.float64)
print(float_arr,float_arr.shape,float_arr.dtype)

(3, 3)
9
int32
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] (3, 3) float64


In [9]:
#operations on arrays
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
reshaped=arr.reshape((3,2))
print(reshaped)
flattened=arr.flatten()
print(flattened)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [10]:
#indexing
arr=np.array([[1,2,3],[4,5,6]])
print(arr[1][1])

5


In [17]:
#Fancy Indexing
arr=np.array([1,2,3,4,5])
idx=[1,2,4]
print(arr[idx])

[2 3 5]


In [20]:
#Boolean Indexing
arr=np.array([1,2,3,4,5])
print(arr[arr>2])
print(arr[arr%2==0])
print(arr[arr%2!=0])

[3 4 5]
[2 4]
[1 3 5]


In [24]:
#slicing
arr=np.array([1,2,3,4,5])
print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]


In [25]:
#Copy vs View
# nums = [1, 2, 3, 4, 5]
# sub_list = nums[1:3]
# print(sub_list)
# sub_list[0] = 200

# print(sub_list)
# print(nums)

arr = np.array([1, 2, 3, 4, 5])
sub_arr = arr[1:3].copy()
print(sub_arr)

sub_arr[0] = 200

print(sub_arr)
print(arr)

[2 3]
[200   3]
[1 2 3 4 5]


In [29]:
#data type
arr=np.array(["prime",1,2,3,3.14])
print(arr,arr.dtype)

['prime' '1' '2' '3' '3.14'] <U32


In [30]:
#complex nums
arr1=np.array([3+5j])
arr2=np.array([2+3j])
print(arr1+arr2)


[5.+8.j]


In [31]:
#objects
arr=np.array(["sigma",{1,2,3},3.14])
print(arr,arr.dtype)

['sigma' {1, 2, 3} 3.14] object


In [32]:
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(np.sum(arr2D))          # sum of entire array - 45

sum_of_columns = np.sum(arr2D, axis=0)
print(sum_of_columns)         # [12 15 18]

sum_of_rows = np.sum(arr2D, axis=1)
print(sum_of_rows)            # [6 15 24]

# Slicing
print(arr2D[0:3, 1:3])       # slice rows(0,1,2) x cols(1,2)
                              # [[2 3]
                              #  [5 6]
                              #  [8 9]]

45
[12 15 18]
[ 6 15 24]
[[2 3]
 [5 6]
 [8 9]]
