In [1]:
import numpy as np
import time

In [2]:
arr=np.array([1,2,3,4,5])
print(arr,type(arr),arr.shape)
arr2=np.array([1,2,3,4,"prime"])
print(arr2,type(arr2),arr2.shape)
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D,arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' 'prime'] <class 'numpy.ndarray'> (5,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
